version: '3.8'

services:
  db-legal:
    image: postgres:15-alpine
    container_name: db-legal-pro
    restart: always
    volumes:
      - v_db_legal_pro:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: ${LEGAL_DB_USER:-toxiro_admin}
      POSTGRES_PASSWORD: ${LEGAL_DB_PASSWORD}
      POSTGRES_DB: ${LEGAL_DB_NAME:-legal_db}
    networks:
      - net-pro

  db-whatsapp:
    image: postgres:15-alpine
    container_name: db-whatsapp-pro
    restart: always
    environment:
      POSTGRES_USER: ${EVO_DB_USER:-evolution_admin}
      POSTGRES_PASSWORD: ${EVO_DB_PASSWORD}
      POSTGRES_DB: ${EVO_DB_NAME:-evolution_db}
    volumes:
      - v_db_whatsapp_pro:/var/lib/postgresql/data
    networks:
      - net-pro

  api-legal:
    image: directus/directus:latest
    container_name: api-legal-pro
    restart: always
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      DB_CLIENT: "pg"
      DB_HOST: "db-legal"
      DB_PORT: "5432"
      DB_DATABASE: ${LEGAL_DB_NAME:-legal_db}
      DB_USER: ${LEGAL_DB_USER:-toxiro_admin}
      DB_PASSWORD: ${LEGAL_DB_PASSWORD}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@toxirodigital.cloud}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
    depends_on:
      - db-legal
    networks:
      - net-pro

  whatsapp-api:
    image: atendai/evolution-api:v2.2.0
    container_name: whatsapp-api-pro
    restart: always
    environment:
      AUTHENTICATION_API_KEY: ${EVO_API_KEY}
      AUTHENTICATION_TYPE: "apikey"
      SERVER_TYPE_HTTP: "true"
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://${EVO_DB_USER:-evolution_admin}:${EVO_DB_PASSWORD}@db-whatsapp:5432/${EVO_DB_NAME:-evolution_db}"
      DATABASE_CONNECTION_CLIENT: "pg"
      CACHE_REDIS_ENABLED: "false"
      CACHE_LOCAL_ENABLED: "true"
      DATABASE_SAVE_DATA_INSTANCE: "false"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_DATA_CONTACTS: "true"
      DATABASE_SAVE_DATA_CHATS: "true"
      INTEGRATIONS: "WHATSAPP-BAILEYS"
    volumes:
      - v_evolution_pro:/evolution/instances
    depends_on:
      - db-whatsapp
    networks:
      - net-pro

networks:
  net-pro:
    driver: bridge

volumes:
  v_db_legal_pro:
  v_evolution_pro:
  v_db_whatsapp_pro:
