version: '3.8'

services:
  db-legal:
    image: postgres:15-alpine
    container_name: db-legal-pro
    restart: always
    volumes:
      - v_db_legal_pro:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: toxiro_admin
      POSTGRES_PASSWORD: toxiro_password_pro_change_me
      POSTGRES_DB: legal_db
    networks:
      - net-pro

  db-whatsapp:
    image: postgres:15-alpine
    container_name: db-whatsapp-pro
    restart: always
    environment:
      POSTGRES_USER: evolution_admin
      POSTGRES_PASSWORD: evolution_password_pro
      POSTGRES_DB: evolution_db
    volumes:
      - v_db_whatsapp_pro:/var/lib/postgresql/data
    networks:
      - net-pro

  api-legal:
    image: directus/directus:latest
    container_name: api-legal-pro
    restart: always
    ports:
      - "8055:8055"
    environment:
      KEY: "legal-factory-vps-key"
      SECRET: "legal-factory-vps-secret"
      DB_CLIENT: "pg"
      DB_HOST: "db-legal"
      DB_PORT: "5432"
      DB_DATABASE: "legal_db"
      DB_USER: "toxiro_admin"
      DB_PASSWORD: "toxiro_password_pro_change_me"
      ADMIN_EMAIL: "admin@toxirodigital.cloud"
      ADMIN_PASSWORD: "admin"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
    depends_on:
      - db-legal
    networks:
      - net-pro

  n8n-legal:
    image: n8nio/n8n:latest
    container_name: n8n-legal-pro
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - v_n8n_pro:/home/node/.n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "toxiro_password_pro_change_me"
    networks:
      - net-pro

  whatsapp-api:
    image: atendai/evolution-api:v2.2.0
    container_name: whatsapp-api-pro
    restart: always
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: "secret_api_key_pro"
      AUTHENTICATION_TYPE: "apikey"
      SERVER_TYPE_HTTP: "true"
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://evolution_admin:evolution_password_pro@db-whatsapp:5432/evolution_db"
      DATABASE_CONNECTION_CLIENT: "pg"
      CACHE_REDIS_ENABLED: "false"
      CACHE_LOCAL_ENABLED: "true"
      DATABASE_SAVE_DATA_INSTANCE: "false" # Sesiones en archivos para velocidad en Linux
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_DATA_CONTACTS: "true"
      DATABASE_SAVE_DATA_CHATS: "true"
      INTEGRATIONS: "WHATSAPP-BAILEYS"
    volumes:
      - v_evolution_pro:/evolution/instances
    depends_on:
      - db-whatsapp
    networks:
      - net-pro

networks:
  net-pro:
    driver: bridge

volumes:
  v_db_legal_pro:
  v_n8n_pro:
  v_evolution_pro:
  v_db_whatsapp_pro:
